### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CanerKaraca23** [Yaya48/Uncursus#13]
I'm getting these errors every installation.

![48DD6FB9-F96A-46D4-8586-9F09ED649570](https://user-images.githubusercontent.com/37447503/89323216-0a04ac80-d68e-11ea-81a1-564c5f9992a3.png)
![6CCF97CA-2A94-4269-BAA7-6EEE39A82E34](https://user-images.githubusercontent.com/37447503/89323225-0bce7000-d68e-11ea-8303-8da84685aa62.png)

**Comment by Yaya48** [comment]
Hi the issues isnt from uncursus, you have an pirated pacakge from an pirated repo, remove all kiimo installed pakackage and the issues will be fixed

**Comment by Fahrenheit** [comment]
Pirate scum
