### ISSUE TITLE
Works but want to go back

### ISSUE THREAD

**Issue by rctfan929** [Yaya48/Uncursus#4]
Your script work fine. But I want to go back to the original. After I do the following I can't get cydia back.

1. Restore RootFS
2. Rejailbreak w/ unc0ver

I also have tried rejailbreaking with reinstall cydia on.

**Comment by Yaya48** [comment]
Hello when you have restore rootfs all uncurus files Is deleted prblem after rootfs restore isn’t cause by uncurus have your tried with refresh cache on?
