### ISSUE TITLE
Switching Compability

### ISSUE THREAD

**Issue by CanerKaraca23** [Yaya48/Uncursus#8]
Hi, I switched my device from checkra1n to unc0ver on iOS 12.4.6. Is it ok? Also I installed Uncursus Installer but it's stucked on this step, I guess script detects my jailbreak checkra1n but isn't.

![8CDA3428-FB11-45FC-B6D8-18D1E5FAB0B4](https://user-images.githubusercontent.com/37447503/89104878-3073df00-d425-11ea-90eb-bcff041e7f2f.png)

**Comment by Yaya48** [comment]
install filza goto / and delete .bootstrapped

**Comment by Yaya48** [comment]
ps do that and i will improve the checker later

**Comment by Yaya48** [comment]
Should work In 2.0.2

**Comment by Yaya48** [comment]
Fixed I close the issues
